/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AshaRouteImport } from './routes/asha'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DistrictRouteImport } from './routes/district'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FacilityDashboardRouteImport } from './routes/facility-dashboard'
import { Route as FollowupRouteImport } from './routes/followup'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as TokenRouteImport } from './routes/token'
import { Route as FacilityIdRouteImport } from './routes/facility/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AshaRoute = AshaRouteImport.update({
  id: '/asha',
  path: '/asha',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictRoute = DistrictRouteImport.update({
  id: '/district',
  path: '/district',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityDashboardRoute = FacilityDashboardRouteImport.update({
  id: '/facility-dashboard',
  path: '/facility-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupRoute = FollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityIdRoute = FacilityIdRouteImport.update({
  id: '/facility/$id',
  path: '/facility/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asha': typeof AshaRoute
  '/chat': typeof ChatRoute
  '/district': typeof DistrictRoute
  '/facilities': typeof FacilitiesRoute
  '/facility-dashboard': typeof FacilityDashboardRoute
  '/followup': typeof FollowupRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/simulator': typeof SimulatorRoute
  '/token': typeof TokenRoute
  '/facility/$id': typeof FacilityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asha': typeof AshaRoute
  '/chat': typeof ChatRoute
  '/district': typeof DistrictRoute
  '/facilities': typeof FacilitiesRoute
  '/facility-dashboard': typeof FacilityDashboardRoute
  '/followup': typeof FollowupRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/simulator': typeof SimulatorRoute
  '/token': typeof TokenRoute
  '/facility/$id': typeof FacilityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asha': typeof AshaRoute
  '/chat': typeof ChatRoute
  '/district': typeof DistrictRoute
  '/facilities': typeof FacilitiesRoute
  '/facility-dashboard': typeof FacilityDashboardRoute
  '/followup': typeof FollowupRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/simulator': typeof SimulatorRoute
  '/token': typeof TokenRoute
  '/facility/$id': typeof FacilityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asha'
    | '/chat'
    | '/district'
    | '/facilities'
    | '/facility-dashboard'
    | '/followup'
    | '/history'
    | '/login'
    | '/simulator'
    | '/token'
    | '/facility/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asha'
    | '/chat'
    | '/district'
    | '/facilities'
    | '/facility-dashboard'
    | '/followup'
    | '/history'
    | '/login'
    | '/simulator'
    | '/token'
    | '/facility/$id'
  id:
    | '__root__'
    | '/'
    | '/asha'
    | '/chat'
    | '/district'
    | '/facilities'
    | '/facility-dashboard'
    | '/followup'
    | '/history'
    | '/login'
    | '/simulator'
    | '/token'
    | '/facility/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AshaRoute: typeof AshaRoute
  ChatRoute: typeof ChatRoute
  DistrictRoute: typeof DistrictRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FacilityDashboardRoute: typeof FacilityDashboardRoute
  FollowupRoute: typeof FollowupRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  SimulatorRoute: typeof SimulatorRoute
  TokenRoute: typeof TokenRoute
  FacilityIdRoute: typeof FacilityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asha': {
      id: '/asha'
      path: '/asha'
      fullPath: '/asha'
      preLoaderRoute: typeof AshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district': {
      id: '/district'
      path: '/district'
      fullPath: '/district'
      preLoaderRoute: typeof DistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility-dashboard': {
      id: '/facility-dashboard'
      path: '/facility-dashboard'
      fullPath: '/facility-dashboard'
      preLoaderRoute: typeof FacilityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followup': {
      id: '/followup'
      path: '/followup'
      fullPath: '/followup'
      preLoaderRoute: typeof FollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/$id': {
      id: '/facility/$id'
      path: '/facility/$id'
      fullPath: '/facility/$id'
      preLoaderRoute: typeof FacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AshaRoute: AshaRoute,
  ChatRoute: ChatRoute,
  DistrictRoute: DistrictRoute,
  FacilitiesRoute: FacilitiesRoute,
  FacilityDashboardRoute: FacilityDashboardRoute,
  FollowupRoute: FollowupRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  SimulatorRoute: SimulatorRoute,
  TokenRoute: TokenRoute,
  FacilityIdRoute: FacilityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
